import type { Currency, StatementFilters, WalletTransaction } from './types';
import { TRANSACTION_TYPE_LABELS } from './transaction-display';

/**
 * Builds the downloadable statement.
 *
 * CSV rather than PDF: an agent's accountant opens this in Excel and
 * reconciles it against their own books, which a PDF makes needlessly hard. A
 * formal, numbered PDF statement belongs with the rest of the document
 * pipeline in issue #46, where templating and gapless numbering already live.
 */

/**
 * Minor units as a plain, ungrouped decimal — `150000` becomes `'1500.00'`.
 *
 * No thousands separators and no currency symbol, unlike the on-screen
 * formatting: a spreadsheet has to parse this back into a number, and
 * `"₦1,500.00"` arrives as text, which silently breaks every SUM written over
 * the column. The currency is named once, in the header row, instead.
 *
 * Integer arithmetic only — see CLAUDE.md rule 2.
 */
export function minorToPlainDecimal(amountMinor: number): string {
  const sign = amountMinor < 0 ? '-' : '';
  const absolute = Math.abs(amountMinor);
  return `${sign}${Math.trunc(absolute / 100)}.${String(absolute % 100).padStart(2, '0')}`;
}

/** Quotes a field and doubles any quotes inside it. RFC 4180. */
function quote(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

/**
 * Quotes a field of free text, defusing it first if a spreadsheet would run it.
 *
 * Excel and Sheets execute a cell beginning with `= + - @`, so a booking
 * described as `=cmd|...` becomes something an accountant is prompted to run.
 * The description and reference columns carry agent- and traveller-supplied
 * text, which is exactly what an attacker would aim at, so they go through
 * here. A leading apostrophe forces the cell to be read as text.
 */
function quoteText(value: string): string {
  return quote(/^[=+\-@\t\r]/.test(value) ? `'${value}` : value);
}

/**
 * Quotes a number.
 *
 * Deliberately NOT `quoteText`: a debit is written `-1500.00`, and defusing its
 * leading minus would turn every outgoing amount into text and make the export
 * useless for the one job it has. These fields are generated by
 * `minorToPlainDecimal`, never by a user, so there is nothing to defuse.
 */
function quoteNumber(value: string): string {
  return quote(value);
}

/** The matching rows, newest first, as CSV text with a header row. */
export function toStatementCsv(rows: WalletTransaction[], currency: Currency): string {
  const header = [
    'Date',
    'Type',
    'Description',
    'Reference',
    `Amount (${currency})`,
    `Balance after (${currency})`,
  ];

  const lines = [
    header.map(quote).join(','),
    ...rows.map((row) =>
      [
        quote(row.occurredAt),
        quote(TRANSACTION_TYPE_LABELS[row.type]),
        quoteText(row.description),
        quoteText(row.reference ?? ''),
        quoteNumber(minorToPlainDecimal(row.amountMinor)),
        quoteNumber(minorToPlainDecimal(row.balanceAfterMinor)),
      ].join(','),
    ),
  ];

  // CRLF and a trailing newline: RFC 4180, and what Excel expects.
  return `${lines.join('\r\n')}\r\n`;
}

/**
 * A filename that says what is in the file, so a folder of these is still
 * readable in six months: `wallet-statement-2026-01-01-to-2026-03-31.csv`.
 */
export function statementFileName(filters: StatementFilters, today = new Date()): string {
  const to = filters.to ?? today.toISOString().slice(0, 10);
  const range = filters.from ? `${filters.from}-to-${to}` : `to-${to}`;
  return `wallet-statement-${range}.csv`;
}
