// Turns openapi.json into src/generated/schema.ts.
//
// Run through `pnpm generate:api` (from frontend/), which first refreshes
// openapi.json from the real API. Running this file on its own only re-renders
// the TypeScript from whatever openapi.json already says.
//
// It is also imported by src/schema-freshness.test.ts, so the test and the
// generator can never disagree about what "up to date" means.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';
import { pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const packageRoot = new URL('..', import.meta.url);
const specUrl = new URL('openapi.json', packageRoot);
const schemaUrl = new URL('src/generated/schema.ts', packageRoot);

const BANNER = `/**
 * GENERATED by \`pnpm generate:api\` from packages/api-client/openapi.json.
 *
 * Do not edit this file. Every change is overwritten by the next generation.
 * To change a type, change the C# record in backend/services/TripsAgent.Contracts
 * and run \`pnpm generate:api\` from frontend/.
 */

`;

/** What schema.ts should contain for the current openapi.json. */
export async function renderSchema() {
  const ast = await openapiTS(specUrl);
  return BANNER + astToString(ast);
}

/** What schema.ts contains now, or null if it has never been generated. */
export async function readCommittedSchema() {
  try {
    return await readFile(schemaUrl, 'utf8');
  } catch {
    return null;
  }
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  await mkdir(new URL('.', schemaUrl), { recursive: true });
  await writeFile(schemaUrl, await renderSchema());
  process.stdout.write(`Wrote ${schemaUrl.pathname}\n`);
}
