namespace TripsAgent.Application.Identity;

/// <summary>
/// Hashes short-lived secrets — OTP codes, reset tokens, refresh tokens — for storage and lookup.
/// </summary>
/// <remarks>
/// <para>
/// Separate from <see cref="IPasswordHasher"/> on purpose. A password is chosen by a person and
/// needs a slow, salted hash to resist guessing. These secrets are generated by us, and they must
/// be <i>looked up</i> by their hash — which a random salt per value would make impossible.
/// </para>
/// <para>
/// So this is a keyed hash (HMAC) instead. The key never touches the database, so a leaked dump
/// on its own cannot be used to brute-force a six-digit code offline: without the key, every
/// guess needs the server.
/// </para>
/// </remarks>
public interface ITokenHasher
{
    /// <summary>A deterministic keyed hash of <paramref name="token"/>, safe to store.</summary>
    public string Hash(string token);

    /// <summary>Generates a cryptographically random numeric code, e.g. an OTP.</summary>
    public string GenerateNumericCode(int digits);

    /// <summary>Generates a cryptographically random, URL-safe opaque token.</summary>
    public string GenerateOpaqueToken();
}
