using System.Globalization;
using System.Security.Cryptography;
using TripsAgent.Application.Storage;

namespace TripsAgent.Infrastructure.Storage;

/// <summary>Where local blob storage keeps its files.</summary>
public sealed class LocalBlobStorageOptions
{
    /// <summary>The directory everything is written beneath.</summary>
    public string RootPath { get; init; } =
        Path.Combine(Path.GetTempPath(), "tripsagent-storage");
}

/// <summary>
/// Stores blobs as files on disk. For local development, and for tests.
/// </summary>
/// <remarks>
/// <para>
/// Deliberately the simplest thing that satisfies <see cref="IBlobStorage"/>. It exists so KYB
/// uploads work on a laptop with nothing else running — no MinIO, no cloud account, no
/// credentials. The MinIO and cloud adapters arrive with the upload pipeline (#18) behind the
/// same interface.
/// </para>
/// <para>
/// Not suitable for production: files sit on one machine's disk, so a second API instance cannot
/// read what the first wrote, and nothing replicates or backs them up.
/// </para>
/// </remarks>
public sealed class LocalFileBlobStorage : IBlobStorage
{
    private readonly string _root;

    public LocalFileBlobStorage(LocalBlobStorageOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        _root = Path.GetFullPath(options.RootPath);
        Directory.CreateDirectory(_root);
    }

    public async Task<StoredBlob> StoreAsync(
        Stream content,
        string key,
        string contentType,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(content);

        var path = ResolvePath(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        long size;
        byte[] checksum;

        await using (var file = File.Create(path))
        using (var sha = SHA256.Create())
        {
            // Hash while writing rather than re-reading afterwards: one pass over the bytes, and
            // the checksum describes exactly what landed on disk.
            await using var hashing = new CryptoStream(file, sha, CryptoStreamMode.Write, leaveOpen: true);

            await content.CopyToAsync(hashing, cancellationToken);
            await hashing.FlushFinalBlockAsync(cancellationToken);

            size = file.Length;
            checksum = sha.Hash!;
        }

        return new StoredBlob(key, size, Convert.ToHexString(checksum).ToLower(CultureInfo.InvariantCulture));
    }

    public Task<Stream> OpenReadAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);

        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"No object stored under key '{key}'.", path);
        }

        return Task.FromResult<Stream>(File.OpenRead(path));
    }

    public Task<bool> ExistsAsync(string key, CancellationToken cancellationToken = default) =>
        Task.FromResult(File.Exists(ResolvePath(key)));

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(key);

        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Turns a storage key into a path inside the root, refusing anything that would escape it.
    /// </summary>
    /// <remarks>
    /// Keys are generated by the application, never taken from a filename — but this is the last
    /// place a traversal could turn into writing outside the storage directory, so it is checked
    /// here rather than trusted.
    /// </remarks>
    private string ResolvePath(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);

        var combined = Path.GetFullPath(Path.Combine(_root, key.Replace('\\', '/')));

        if (!combined.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && !string.Equals(combined, _root, StringComparison.Ordinal))
        {
            throw new ArgumentException($"Storage key '{key}' resolves outside the storage root.", nameof(key));
        }

        return combined;
    }
}
