namespace TripsAgent.Application.Storage;

/// <summary>What was stored, and what it turned out to be.</summary>
/// <param name="StorageKey">Where the bytes now live.</param>
/// <param name="SizeBytes">How many bytes were actually written.</param>
/// <param name="Checksum">SHA-256 of the stored content, hex-encoded.</param>
public sealed record StoredBlob(string StorageKey, long SizeBytes, string Checksum);

/// <summary>
/// A request the browser sends straight to storage, already signed so storage will accept it.
/// </summary>
/// <param name="Url">Where to send the bytes. Absolute for a cloud store; a path on this API locally.</param>
/// <param name="Method">The HTTP method the signature covers — PUT for every provider we expect.</param>
/// <param name="Headers">
/// Headers the client must send exactly as given. An S3 or Azure signature covers some headers, so
/// changing one invalidates the request; carrying them here keeps that a provider detail.
/// </param>
/// <param name="MaxSizeBytes">The most the storage endpoint will accept.</param>
/// <param name="ExpiresAt">When the signature stops working.</param>
public sealed record PresignedUpload(
    string Url,
    string Method,
    IReadOnlyDictionary<string, string> Headers,
    long MaxSizeBytes,
    DateTimeOffset ExpiresAt);

/// <summary>A time-limited link that reads one object, and when it stops working.</summary>
public sealed record SignedDownload(string Url, DateTimeOffset ExpiresAt);

/// <summary>
/// Somewhere to put files. A port, not a provider.
/// </summary>
/// <remarks>
/// <para>
/// The cloud is not chosen yet (CLAUDE.md), so nothing above this line may know whether the bytes
/// end up in S3, Azure Blob Storage or a directory on disk. Local development uses the filesystem;
/// MinIO and then a real provider slot in behind the same interface.
/// </para>
/// <para>
/// Two kinds of member. The stream members move bytes through this process, which is what KYB
/// uploads and the Worker's pipeline do. The signing members move bytes around it: the API hands
/// the browser a signed URL and the file goes straight to storage (issue #18). Every object store
/// worth choosing can sign a PUT and a GET, which is why the second kind is part of the port
/// rather than an optional extra.
/// </para>
/// </remarks>
public interface IBlobStorage
{
    /// <summary>
    /// Stores a stream and returns where it went, how big it was and its checksum.
    /// </summary>
    /// <param name="key">
    /// The full key to store under. Callers generate it; storage never derives one from a
    /// user-supplied filename.
    /// </param>
    public Task<StoredBlob> StoreAsync(
        Stream content,
        string key,
        string contentType,
        CancellationToken cancellationToken = default);

    /// <summary>Opens a stored object for reading. Throws if the key does not exist.</summary>
    public Task<Stream> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    /// <summary>True when an object exists at that key.</summary>
    public Task<bool> ExistsAsync(string key, CancellationToken cancellationToken = default);

    /// <summary>The object's size in bytes, or null when nothing is stored at that key.</summary>
    /// <remarks>A HEAD request on an object store: the size is known without reading the bytes.</remarks>
    public Task<long?> GetSizeAsync(string key, CancellationToken cancellationToken = default);

    /// <summary>Removes an object. Succeeds quietly when it was already gone.</summary>
    public Task DeleteAsync(string key, CancellationToken cancellationToken = default);

    /// <summary>
    /// Signs a request that lets whoever holds it write one object, once, before it expires.
    /// </summary>
    /// <param name="key">The key the bytes must land at. Generated by the caller, never from a filename.</param>
    /// <param name="contentType">The type the client says it is sending. Advisory: the bytes are sniffed afterwards.</param>
    /// <param name="maxSizeBytes">The most the storage endpoint should accept, where the provider can enforce it.</param>
    /// <param name="expiresAt">When the signature stops working.</param>
    public Task<PresignedUpload> CreateUploadUrlAsync(
        string key,
        string contentType,
        long maxSizeBytes,
        DateTimeOffset expiresAt,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Signs a link that reads one object until it expires.
    /// </summary>
    /// <remarks>
    /// Signing a link is not a decision to serve. Callers decide whether an object may be seen
    /// before asking for one — for assets that is <c>AssetDelivery</c>, and nothing else.
    /// </remarks>
    public Task<SignedDownload> CreateDownloadUrlAsync(
        string key,
        string contentType,
        DateTimeOffset expiresAt,
        CancellationToken cancellationToken = default);
}
